# Generated by Django 4.2.1 on 2023-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="joined_on",
            field=models.TimeField(auto_now=True),
        ),
    ]
