# Generated by Django 4.2.1 on 2023-07-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_method_permission_remove_role_discription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="method",
            field=models.ManyToManyField(to="account.method"),
        ),
        migrations.AddField(
            model_name="role",
            name="permission",
            field=models.ManyToManyField(to="account.permission"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="account.role"
            ),
        ),
        migrations.DeleteModel(
            name="RolePermission",
        ),
    ]
