# Generated by Django 4.2.1 on 2023-07-22 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_remove_permission_method_permission_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="created_by",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
