exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-builtin-literals
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: name-tests-test
        args: [ "--django" ]


-   repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ['-iii', '-ll']


-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3.11


-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)


-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.31.1
    hooks:
    -   id: djlint-reformat-django
    -   id: djlint-django
