# Generated by Django 4.2.1 on 2023-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="update_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
